[workspace]
members = [
    "helicoid-client",
    "helicoid-protocol",
    "helicoid-helixserver",
    "helicoid-testserver",
    "helicoid-gpurender",
    "helicoid-wgpu",
]

default-members = [
    "helicoid-client"
]
resolver = "2"

[patch.crates-io]
rkyv = { git = "https://github.com/rkyv/rkyv.git"}
ordered-float = { git = "https://github.com/freqmod/rust-ordered-float.git"}
winit = { git = "https://github.com/freqmod/winit.git", branch="keys"}
