[package]
name = "helicoid"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
copypasta = "0.8.1"
async-trait = "0.1.53"
backtrace = "0.3.67"
cfg-if = "1.0.0"
clap = { version = "4.0.8", features = ["cargo", "derive", "env"] }
csscolorparser = "0.6.2"
derive-new = "0.5.9"
dirs = "4.0.0"
euclid = "0.22.7"
flexi_logger = { version = "0.22.3", default-features = false }
env_logger = {version = "0.10" }
futures = "0.3.21"
gl = "0.14.0"
glutin = { git = "https://github.com/neovide/glutin", branch = "new-keyboard-all", features = ["serde"] }
image = { version = "0.24.1", default-features = false, features = ["ico"] }
itertools = "0.10.5"
lazy_static = "1.4.0"
log = "0.4.16"
lru = "0.7.5"
nvim-rs = { git = "https://github.com/KillTheMule/nvim-rs", branch = "master", features = ["use_tokio"] }
parking_lot = "0.12.0"
pin-project = "1.0.10"
rand = "0.8.5"
rmpv = "1.0.0"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
shlex = "1.1.0"
swash = "0.1.4"
time = "0.3.9"
tokio = { version = "1.17.0", features = ["full"] }
tokio-util = { version = "0.7.1", features = ["compat"] }
unicode-segmentation = "1.9.0"
which = "4.2.5"
winit = { git = "https://github.com/neovide/winit", branch = "new-keyboard-all" }
xdg = "2.4.1"

[dev-dependencies]
mockall = "0.11.0"


[target.'cfg(linux)'.dependencies.skia-safe]
features = ["gl", "egl"]
version = "0.52.0"

[target.'cfg(not(linux))'.dependencies.skia-safe]
features = ["gl"]
version = "0.52.0"
