[workspace]
members = [
    "helicoid-client",
    "helicoid-protocol",
    "helicoid-testserver",
]

default-members = [
    "helicoid-client"
]

[patch.crates-io]
rkyv = { git = "https://github.com/rkyv/rkyv.git"}
winit = { git = "https://github.com/freqmod/winit.git", branch="keys"}
