[workspace]
members = [
    "helicoid-client",
    "helicoid-protocol",
    "helicoid-testserver",
]

default-members = [
    "helicoid-client"
]

[patch.crates-io]
rkyv = { path = "../../Downloads/rkyv/rkyv" }